CREATE TABLE IF NOT EXISTS resource_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    content_type  VARCHAR(128) NOT NULL,
    size_bytes    BIGINT       NOT NULL,
    sha256        VARCHAR(64)  NOT NULL,
    storage_name  VARCHAR(64)  NOT NULL,
    created_at    BIGINT       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_resource_item_sha256 ON resource_item (sha256);
CREATE INDEX IF NOT EXISTS idx_resource_item_created_at ON resource_item (created_at);
